return {
  ui = {
    bug = '',
    clock = '',
    tab = '󰌒',
    carret_right = '',
    carret_left = '',
    carret_down = '',
    carret_up = '',
  },
  file = {
    modified = '',
    readonly = '',
  },
  diagnostics = {
    hint = '',
    error = ' ',
    warn = ' ',
    info = ' ',
    information = ' ',
    other = ' ',
  },
  git = {
    added = ' ',
    modified = ' ',
    removed = ' ',
    deleted = '✖',
    renamed = '󰁕',
    untracked = '',
    ignored = '◌',
    unstaged = '󰄱',
    staged = '',
    conflict = '',
  },
}
