require'mpa.opts'
require'mpa.keymaps'
require'mpa.autocmds'
require'mpa.diagnostics'

require'plugins.colorscheme'
require'plugins.treesitter'
require'plugins.which-key'
require'plugins.mini'
require'plugins.neo-tree'
require'plugins.ufo'
require'plugins.tmux'
require'plugins.lsp'
require'plugins.blink'
